/* ----------------------  Counting each individuals or clients per city ----------------------------- */



CREATE TABLE Clients (

  client_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  client_firstname VARCHAR(255) NOT NULL,
  client_lastname VARCHAR(255) NOT NULL,
  age INT NOT NULL,
  city VARCHAR(255)
); 

INSERT INTO Clients (client_id, client_firstname, client_lastname, age, city)
VALUES (101, 'Samantha', 'Dela Cruz', 20, 'Makati'),
       (102, 'Mark', 'Floro', 19, 'Makati'),
       (103, 'Rafael', 'Billedo', 20, 'Taguig'),
       (104, 'Cedric', 'Fernandez', 20, 'Marikina'),
       (105, 'Anthony', 'Bandala', 19, 'Pasig'),
       (106, 'Dylan', 'Nigasama', 19, 'Taguig'),
       (107, 'Nathaniel', 'Gomez', 19, 'Antipolo'),
       (108, 'Crey', 'Merina', 22, 'Makati'),
       (109, 'Christopher', 'Enriquez', 22, 'Taguig'),
       (110, 'Izza', 'Chiong', 20, 'Antipolo');



SELECT city, COUNT(client_firstname) AS 'Population Of Clients Per City'
FROM Clients
GROUP BY city
HAVING COUNT(client_firstname) >= 1
ORDER BY COUNT(client_firstname) ASC ; 


/* ------------------------------------------------------------------------------------- * /




/*  ---------------------------- Calculating the Total Revenue Each Products Generated ------------------------------------ */

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(50),
    category VARCHAR(50),
    price DECIMAL(10,2)
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    product_id INT,
    quantity INT,
    order_date DATE
);

INSERT INTO products VALUES 
(1, 'Laptop', 'Electronics', 1000.00),
(2, 'Mouse', 'Electronics', 50.00),
(3, 'Desk Chair', 'Furniture', 150.00),
(4, 'Notebook', 'Stationery', 5.00),
(5, 'Keyboard', 'Electronics', 80.00);

INSERT INTO orders VALUES 
(101, 1, 2, '2026-01-10'),
(102, 2, 5, '2026-01-11'),
(103, 3, 1, '2026-01-12'),
(104, 4, 20, '2026-01-12'),
(105, 5, 3, '2026-01-13'),
(106, 1, 1, '2026-01-14'),
(107, 2, 2, '2026-01-15');

SELECT 	Products.product_name, 
		    SUM(Orders.quantity * Products.price) AS 'Total Revenue Generated By The Product'
FROM Products
JOIN Orders ON Orders.product_id = Products.product_id
GROUP BY Products.product_name
HAVING SUM(Orders.quantity * Products.price) > 2
ORDER BY SUM(Orders.quantity * Products.price) DESC;






/* -------------------NOTE: JUST COPY THE CODE, DO NOT MIND THE COMMENTS------------------------------------------------------------------------ */


















